In [2]:
import numpy as np
import qutip as qt

# Single-Qubit QST

the density matrix can be estimated by \cite{nielsen_chuang_2019}
\begin{equation}
    \rho_{est}=\frac{1}{2}[\operatorname{tr}(\rho) I+\operatorname{tr}(X \rho) X+\operatorname{tr}(Y \rho) Y+\operatorname{tr}(Z \rho) Z]
    \label{rho_est}
\end{equation}

In [20]:
#Define Pauli matricies
I=qt.qeye(2)
X=qt.sigmax()
Y=qt.sigmay()
Z=qt.sigmaz()

In [12]:
#Define an arbitrary density matrix
rho=qt.Qobj([[0.045,0.182+0.086j],[0.182-0.086j,0.955]])
rho

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.045+0.j    0.182+0.086j]
 [0.182-0.086j 0.955+0.j   ]]

In [40]:
rz=(rho*Z).tr()
rz

-0.9099999999999999

In [41]:
ry=(rho*Y).tr()
ry

-0.172

In [42]:
rx=(rho*X).tr()
rx

0.364

In [60]:
rho_est=(1/2)*(I+rz*Z+ry*Y+rx*X)
rho_est

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.045+0.j    0.182+0.086j]
 [0.182-0.086j 0.955+0.j   ]]

# Two-Qubit QST

In [46]:
#We do a QST on one of the bell states
Bell=qt.bell_state('00')*qt.bell_state('00').dag()
Bell

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.5 0.  0.  0.5]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.5 0.  0.  0.5]]

In [61]:
#Since the number of measurements increase exponentially with the number of qubits...
#instead of doing the pauli measurements in separace cells...
#We make a for loop that tensor product all the different compination of the pauli matrices
#This loop can be modified to any number of qubits but with so many nested loops it will become very ugly

#a set of pauli matrices
pauli_set=[I,X,Y,Z]

#initialize the estimate density matrix to zeros
rho_est=Bell*0

#QST loop
for i in range(4):
    for j in range(4):
        P=qt.tensor(pauli_set[i],pauli_set[j])
        term=(1/2**2)*((P*Bell).tr())*P
        rho_est=rho_est+term
        
rho_est

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.5 0.  0.  0.5]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.5 0.  0.  0.5]]